In [4]:
import numpy as np

In [3]:
#np is the name given to numpy to call

In [4]:
l=[1,2,3,4]

In [5]:
np.array(l)

array([1, 2, 3, 4])

#array are two ways 
vectors - single dimensional
matrix - multi dimensioanl

In [7]:
m=[[1,2,3], [4,5,6], [7,8,9]]

In [8]:
np.array(m)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [11]:
#arange is simlar to range and create by split the values

In [13]:
np.linspace(0,25,5)

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  ])

In [14]:
#linspace is equally diveded space b/w the values

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.35553078, 0.72327608, 0.51110511, 0.70638696, 0.19375273])

In [21]:
np.random.randn(5)

array([-0.30592553, -0.61125457,  0.74059486, -0.05629831, -0.19758361])

In [22]:
np.random.randint(10,100,5)

array([92, 66, 71, 31, 68])

In [24]:
np.random.rand(3,4)

array([[7.17695499e-01, 8.55197659e-01, 4.44473831e-01, 7.71138779e-01],
       [9.35304568e-01, 7.85214775e-01, 5.36258927e-01, 2.79933268e-01],
       [6.74432433e-04, 3.13755679e-02, 2.49426417e-01, 9.66478567e-01]])

In [25]:
np.random.randint(10,100,(3,4))

array([[46, 36, 55, 13],
       [31, 75, 48, 89],
       [54, 31, 74, 37]])

In [21]:
a=np.random.randint(0,100,25)

In [22]:
a

array([65,  6, 49, 31, 38, 22, 43, 64, 84, 97, 98, 66, 41, 97, 93, 15, 43,
       98, 83, 61, 68, 79, 56, 26, 34])

In [28]:
a.max()

99

In [29]:
a.min()

3

In [30]:
a.argmax()

1

In [31]:
a.argmin()

13

In [32]:
a.shape

(30,)

In [33]:
a

array([32, 99, 89, 14, 82, 18, 50, 88, 21, 48, 25, 34, 45,  3, 75, 12, 13,
        5, 90, 92, 22, 79, 92, 19, 63,  3, 89, 92, 79,  3])

In [23]:
a1=a.reshape(5,5)

In [27]:
a1

array([[65,  6, 49, 31, 38],
       [22, 43, 64, 84, 97],
       [98, 66, 41, 97, 93],
       [15, 43, 98, 83, 61],
       [68, 79, 56, 26, 34]])

In [35]:
a.dtype

dtype('int32')

In [24]:
b=np.random.randint(0,100,25)

In [25]:
b1=b.reshape(5,5)

In [28]:
b1

array([[82, 44, 76, 65, 51],
       [ 2,  6,  3, 73, 98],
       [31, 96, 15, 21, 40],
       [37, 30, 76, 37, 84],
       [60, 25, 12, 85, 71]])

In [29]:
c=a1*b1

In [30]:
c

array([[5330,  264, 3724, 2015, 1938],
       [  44,  258,  192, 6132, 9506],
       [3038, 6336,  615, 2037, 3720],
       [ 555, 1290, 7448, 3071, 5124],
       [4080, 1975,  672, 2210, 2414]])

In [31]:
c.dtype

dtype('int32')

In [32]:
d=a1-b1

In [33]:
d

array([[-17, -38, -27, -34, -13],
       [ 20,  37,  61,  11,  -1],
       [ 67, -30,  26,  76,  53],
       [-22,  13,  22,  46, -23],
       [  8,  54,  44, -59, -37]])

In [35]:
d1=d.reshape(1,25)

In [37]:
def sqr(a):
    return a**3

In [38]:
list(map(sqr, d1))

[array([  -4913,  -54872,  -19683,  -39304,   -2197,    8000,   50653,
         226981,    1331,      -1,  300763,  -27000,   17576,  438976,
         148877,  -10648,    2197,   10648,   97336,  -12167,     512,
         157464,   85184, -205379,  -50653], dtype=int32)]

In [39]:
a=np.arange(0,10)

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[3]

3

In [42]:
a[-7]

3

In [43]:
a[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [44]:
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
l=[1,2,3,4,5,6]

In [46]:
l1=l.copy()

In [47]:
l1

[1, 2, 3, 4, 5, 6]

In [48]:
l1[3]=30

In [49]:
l1

[1, 2, 3, 30, 5, 6]

In [50]:
l

[1, 2, 3, 4, 5, 6]

In [51]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
b=a.copy()

In [53]:
b[3:6]=737

In [54]:
b

array([  0,   1,   2, 737, 737, 737,   6,   7,   8,   9])

In [55]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b[2:6]=[33,55,66,22]

In [58]:
b

array([ 0,  1, 33, 55, 66, 22,  6,  7,  8,  9])

In [59]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a[[2,8,1]]

array([2, 8, 1])

In [66]:
a=np.random.randint(0,10,6)

In [67]:
a

array([3, 6, 1, 8, 6, 1])

In [68]:
a[[2,4,1]]

array([1, 6, 6])

In [69]:
a=np.random.randint(10,100,(4,5))

In [70]:
a

array([[90, 36, 33, 30, 49],
       [78, 43, 37, 62, 10],
       [84, 49, 44, 16, 46],
       [65, 74, 92, 66, 91]])

In [71]:
a[1][2]

37

In [72]:
a[1,2]

37

In [73]:
a[1:3, 2:4]

array([[37, 62],
       [44, 16]])

In [75]:
np.random.seed(101)
m=np.random.randint(10,100,(6,7))
m

array([[21, 91, 80, 73, 97, 85, 19],
       [87, 50, 14, 73, 50, 70, 74],
       [15, 22, 50, 59, 93, 18, 39],
       [69, 44, 54, 82, 29, 20, 86],
       [97, 10, 83, 18, 72, 46, 93],
       [38, 73, 17, 20, 62, 66, 48]])

In [79]:
m[1:5,3:6]

array([[73, 50, 70],
       [59, 93, 18],
       [82, 29, 20],
       [18, 72, 46]])

In [87]:
m[3:6,6:7]

array([[86],
       [93],
       [48]])

In [90]:
m[2:6, 3:4]

array([[59],
       [82],
       [18],
       [20]])

In [91]:
m[3,4:7]

array([29, 20, 86])

In [94]:
m[:6,4:5]

array([[97],
       [50],
       [93],
       [29],
       [72],
       [62]])